/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.cadastro;

import DAO.QuartoDAO;
import enumeradores.TipoQuartoEnum;
import java.sql.Array;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import model.Quarto;
import view.MenuBar;

/**
 *
 * @author Renan
 */
public class TelaCadastroQuarto extends javax.swing.JFrame {

    private DefaultComboBoxModel<String> modelStringComboBox = new DefaultComboBoxModel<>();

    private void carregaComboBoxTipoQuarto() {
        cbTipoQuarto.setModel(modelStringComboBox);
        cbTipoQuarto.removeAllItems();

        for (TipoQuartoEnum obj : TipoQuartoEnum.values()) {
            cbTipoQuarto.addItem(obj.getDescricao());
        }
    }

    public TelaCadastroQuarto() {
        super("Novo quarto");

        MenuBar menuBar = new MenuBar();
        menuBar.carregaMenuBar(this);

        initComponents();

        carregaComboBoxTipoQuarto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbTipoQuarto = new javax.swing.JComboBox<>();
        txtValorQuarto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnCadastrarQuarto = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtValorQuarto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValorQuartoKeyTyped(evt);
            }
        });

        jLabel1.setText("Valor");

        btnCadastrarQuarto.setText("Cadastrar");
        btnCadastrarQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarQuartoActionPerformed(evt);
            }
        });

        jLabel2.setText("Tipo de quarto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(101, 101, 101))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnCadastrarQuarto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                        .addComponent(cbTipoQuarto, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtValorQuarto, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbTipoQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtValorQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCadastrarQuarto)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarQuartoActionPerformed

        if ("".equals(txtValorQuarto.getText())) {
            JOptionPane.showMessageDialog(this, "Valor em branco!");
            return;
        }

        QuartoDAO quartoDao = new QuartoDAO();
        Quarto quarto = new Quarto();

        quarto.setDisponivel(true);
        quarto.setValor(Float.valueOf(txtValorQuarto.getText()));

        /*Verifica qual descricao do TipoQuartoEnum é igual a descricao da comboTipoQuarto,
        então atribui ao objeto quarto*/
        for (TipoQuartoEnum value : TipoQuartoEnum.values()) {
            if (cbTipoQuarto.getSelectedItem() == value.getDescricao()) {
                quarto.setTipo(value);
            }
        }

        try {
            
            quartoDao.cadastrar(quarto);
            JOptionPane.showMessageDialog(this, "Quarto cadastrado com sucesso!");
            
            txtValorQuarto.setText("");
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaCadastroQuarto.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TelaCadastroQuarto.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnCadastrarQuartoActionPerformed

    private void txtValorQuartoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorQuartoKeyTyped
        String caracteres;
        if (txtValorQuarto.getText().contains(".")) {
            caracteres = "0987654321";
        } else {
            caracteres = "0987654321.";
        }
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtValorQuartoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Windows (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroQuarto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroQuarto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroQuarto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroQuarto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroQuarto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarQuarto;
    private javax.swing.JComboBox<String> cbTipoQuarto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtValorQuarto;
    // End of variables declaration//GEN-END:variables
}
