/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.cadastro;

import DAO.EstadiaDAO;
import DAO.ReservaDAO;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Estadia;
import model.Reserva;
import view.MenuBar;

/**
 *
 * @author Renan
 */
public class TelaCadastroEstadia extends javax.swing.JFrame {

    private final DefaultTableModel modelo = new DefaultTableModel();

    private void carregaTabela() {
        tabelaEstadia.setModel(modelo);

        modelo.addColumn("Reserva");
        modelo.addColumn("CPF Alocado");
        modelo.addColumn("Quarto");
        modelo.addColumn("Data entrada");
        modelo.addColumn("Data saida");

        tabelaEstadia.getColumnModel().getColumn(0).setPreferredWidth(50);
        tabelaEstadia.getColumnModel().getColumn(1).setMinWidth(100);
        tabelaEstadia.getColumnModel().getColumn(2).setPreferredWidth(20);
        tabelaEstadia.getColumnModel().getColumn(3).setPreferredWidth(50);
        tabelaEstadia.getColumnModel().getColumn(4).setPreferredWidth(50);

        pesquisar(modelo);

    }

    public void pesquisar(DefaultTableModel model) {

        try {
            model.setRowCount(0);//Limpa linhas da tabela
            ReservaDAO dao = new ReservaDAO();

            for (Reserva r : dao.exibirViewTabelaReserva()) {

                if (!r.temEstadia()) {
                    model.addRow(new Object[]{r.getId(), r.getHospede().getCpf(),
                        r.getQuarto().getId(), formataData(r.getDataEntrada()), formataData(r.getDataSaida())});
                }

            }
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar a tabela de reservas\n"
                    + "Erro de classe não encontrada:\n" + ex.getMessage());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar a tabela de reservas\n"
                    + "Erro SQL:\n" + ex.getMessage());
        }
    }

    private String formataData(Date data) {
        try {

            String start_dt = data.toString();

            DateFormat parser = new SimpleDateFormat("yyyy-MM-dd");
            Date date = parser.parse(start_dt);

            DateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
            String finalForm = formatter.format(date);
            return finalForm;

        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao formatar a data para carregar a tabela:\n" + ex.getMessage());
        }
        return null;
    }

    public TelaCadastroEstadia() {
        super("Nova estadia");
        initComponents();

        carregaTabela();

        MenuBar menuBar = new MenuBar();
        menuBar.carregaMenuBar(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaEstadia = new javax.swing.JTable();
        txtDataEntrada = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblIdReserva = new javax.swing.JLabel();
        btnCadastrarEstadia = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabelaEstadia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelaEstadia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaEstadiaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelaEstadia);

        jLabel1.setText("Data de entrada");

        jLabel5.setText("Numero da reserva");

        lblIdReserva.setText("0");

        btnCadastrarEstadia.setText("Cadastrar");
        btnCadastrarEstadia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarEstadiaActionPerformed(evt);
            }
        });

        jLabel6.setText("Reservas sem estadia");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(28, 28, 28)
                                .addComponent(lblIdReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtDataEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnCadastrarEstadia, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDataEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(lblIdReserva))
                .addGap(18, 18, 18)
                .addComponent(btnCadastrarEstadia)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarEstadiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarEstadiaActionPerformed
        if (tabelaEstadia.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Por favor, selecione uma reserva da tabela!");
            return;
        }

        try {

            EstadiaDAO estadiaDao = new EstadiaDAO();
            ReservaDAO reservaDao = new ReservaDAO();

            Reserva reserva = reservaDao.buscarPorId(Integer.parseInt(lblIdReserva.getText()));

            Estadia estadia = new Estadia();

            estadia.setDataEntrada(criaData(txtDataEntrada.getText()));
            estadia.setValorTotalServicos(0);
            estadia.setReserva(reserva);

            estadiaDao.cadastrar(estadia);
            reservaDao.alocaEstadiaReserva(reserva);

            pesquisar(modelo);

            JOptionPane.showMessageDialog(this, "Nova estadia cadastrada!");
            
            txtDataEntrada.setText("");
            lblIdReserva.setText("0");

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaCadastroEstadia.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TelaCadastroEstadia.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao formatar a data para cadastro:\n" + ex.getMessage());
        }

    }//GEN-LAST:event_btnCadastrarEstadiaActionPerformed

    private void tabelaEstadiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaEstadiaMouseClicked
        try {
            ReservaDAO reservaDao = new ReservaDAO();
            Reserva reserva = reservaDao.buscarPorId((int) tabelaEstadia.getValueAt(tabelaEstadia.getSelectedRow(), 0));

            txtDataEntrada.setText(String.valueOf(tabelaEstadia.getValueAt(tabelaEstadia.getSelectedRow(), 3)));
            lblIdReserva.setText(String.valueOf(reserva.getId()));

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaCadastroEstadia.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TelaCadastroEstadia.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tabelaEstadiaMouseClicked

    public Date criaData(String data) throws ParseException {

        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        Date dataFormatada = sdf.parse(data);

        return dataFormatada;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Windows (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroEstadia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroEstadia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroEstadia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroEstadia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroEstadia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarEstadia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblIdReserva;
    private javax.swing.JTable tabelaEstadia;
    private javax.swing.JTextField txtDataEntrada;
    // End of variables declaration//GEN-END:variables
}
