/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import view.cadastro.TelaCadastroReserva;
import DAO.QuartoDAO;
import DAO.ReservaDAO;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Quarto;
import model.Reserva;

/**
 *
 * @author Renan
 */
public class TelaReserva extends javax.swing.JFrame {

    private final DefaultTableModel modelo = new DefaultTableModel();

    private void carregaTabela() {
        tabelaReservas.setModel(modelo);

        modelo.addColumn("Reserva");
        modelo.addColumn("CPF Alocado");
        modelo.addColumn("Quarto");
        modelo.addColumn("Data entrada");
        modelo.addColumn("Data saida");

        tabelaReservas.getColumnModel().getColumn(0).setPreferredWidth(50);
        tabelaReservas.getColumnModel().getColumn(1).setMinWidth(100);
        tabelaReservas.getColumnModel().getColumn(2).setPreferredWidth(20);
        tabelaReservas.getColumnModel().getColumn(3).setPreferredWidth(50);
        tabelaReservas.getColumnModel().getColumn(4).setPreferredWidth(50);

        pesquisar(modelo);

    }

    public void pesquisar(DefaultTableModel model) {

        try {
            model.setRowCount(0);//Limpa linhas da tabela
            ReservaDAO dao = new ReservaDAO();

            for (Reserva r : dao.exibirViewTabelaReserva()) {
                model.addRow(new Object[]{r.getId(), r.getHospede().getCpf(),
                    r.getQuarto().getId(), r.getDataEntrada(), r.getDataSaida()});

            }
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar a tabela de reservas\n"
                    + "Erro de classe não encontrada:\n" + ex.getMessage());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar a tabela de reservas\n"
                    + "Erro SQL:\n" + ex.getMessage());
        }
    }

    public TelaReserva() {

        super("Reservas");
        
        initComponents();

        MenuBar menuBar = new MenuBar();
        menuBar.carregaMenuBar(this);

        carregaTabela();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaReservas = new javax.swing.JTable();
        btnCancelarReserva = new javax.swing.JButton();
        btnNovaReserva = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        tabelaReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelaReservas);

        btnCancelarReserva.setText("Cancelar Reserva");
        btnCancelarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarReservaActionPerformed(evt);
            }
        });

        btnNovaReserva.setText("Nova Reserva");
        btnNovaReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovaReservaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNovaReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelarReserva)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarReserva)
                    .addComponent(btnNovaReserva))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovaReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovaReservaActionPerformed

        new TelaCadastroReserva().setVisible(true);

    }//GEN-LAST:event_btnNovaReservaActionPerformed

    private void btnCancelarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarReservaActionPerformed

        if (tabelaReservas.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Por favor, selecione uma reserva da tabela");
            return;
        }

        int valor = (int) tabelaReservas.getValueAt(tabelaReservas.getSelectedRow(), 0);

        int op = JOptionPane.showConfirmDialog(this, "Deseja realmente cancelar a reserva " + valor + "?",
                "Confirmação", JOptionPane.YES_NO_OPTION);

        if (op == JOptionPane.YES_OPTION) {

            try {

                ReservaDAO reservaDao = new ReservaDAO();
                Reserva reserva = reservaDao.buscarPorId(valor);
                reservaDao.excluir(reserva);

                QuartoDAO quartoDao = new QuartoDAO();
                Quarto quarto = quartoDao.buscarPorId(reserva.getQuarto().getId());
                quartoDao.desocuparQuarto(quarto);

                JOptionPane.showMessageDialog(this, "Reserva cancelada. Quarto descocupado!");

            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(this, "Erro ao cancelar reserva\n"
                        + "Erro de classe não encontrada:\n" + ex.getMessage());
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Erro ao cancelar reserva\n"
                        + "Erro SQL:\n" + ex.getMessage());
            }
        }

        pesquisar(modelo);
    }//GEN-LAST:event_btnCancelarReservaActionPerformed

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged


    }//GEN-LAST:event_formWindowStateChanged

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained

    }//GEN-LAST:event_formFocusGained

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus

    }//GEN-LAST:event_formWindowGainedFocus

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

        
        
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaReserva().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarReserva;
    private javax.swing.JButton btnNovaReserva;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaReservas;
    // End of variables declaration//GEN-END:variables
}
