/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import DAO.DAO;
import model.Quarto;
import DAO.QuartoDAO;
import DAO.ReservaDAO;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Reserva;
import view.cadastro.TelaCadastroQuarto;

/**
 *
 * @author Renan
 */
public class TelaQuarto extends javax.swing.JFrame {

    private DefaultTableModel modelo = new DefaultTableModel();

    private void carregaTabela() throws ClassNotFoundException, SQLException {

        tabelaQuartos.setModel(modelo);

        modelo.addColumn("ID");
        modelo.addColumn("Tipo");
        modelo.addColumn("Disponivel");
        modelo.addColumn("Valor");

        tabelaQuartos.getColumnModel().getColumn(0).setMaxWidth(30);
        tabelaQuartos.getColumnModel().getColumn(1).setMinWidth(100);
        tabelaQuartos.getColumnModel().getColumn(2).setPreferredWidth(30);
        tabelaQuartos.getColumnModel().getColumn(3).setPreferredWidth(30);

        pesquisar(modelo);
    }

    public static void pesquisar(DefaultTableModel model) {

        try {
            model.setRowCount(0);//Limpa linhas da tabela
            DAO<Quarto> dao = new QuartoDAO();

            for (Quarto q : dao.exibirTodos()) {
                model.addRow(new Object[]{q.getId(), q.getTipo(), q.isDisponivel(), q.getValor()});

                if (q.isDisponivel()) {

                }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaHospede.class
                    .getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao procurar a classe QUARTO: " + ex.getMessage());
        }

    }

    public TelaQuarto() {
        super("Quartos");
        MenuBar menuBar = new MenuBar();
        menuBar.carregaMenuBar(this);

        try {

            initComponents();
            carregaTabela();

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaHospede.class
                    .getName()).log(Level.SEVERE, null, ex);

        } catch (SQLException ex) {
            Logger.getLogger(TelaHospede.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaQuartos = new javax.swing.JTable();
        btnNovoQuarto = new javax.swing.JButton();
        btnAlterarQuarto = new javax.swing.JButton();
        btnExcluirQuarto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabelaQuartos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tipo", "Ocupado", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaQuartos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaQuartosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelaQuartos);

        btnNovoQuarto.setText("Novo quarto");
        btnNovoQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoQuartoActionPerformed(evt);
            }
        });

        btnAlterarQuarto.setText("Alterar");

        btnExcluirQuarto.setText("Excluir");
        btnExcluirQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirQuartoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNovoQuarto)
                        .addGap(18, 18, 18)
                        .addComponent(btnAlterarQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluirQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovoQuarto)
                    .addComponent(btnAlterarQuarto)
                    .addComponent(btnExcluirQuarto))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelaQuartosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaQuartosMouseClicked


    }//GEN-LAST:event_tabelaQuartosMouseClicked

    private void btnExcluirQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirQuartoActionPerformed
        if (tabelaQuartos.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Por favor, selecione um quarto da tabela");
            return;
        }
        try {
            
            int op;
            QuartoDAO quartoDao = new QuartoDAO();
            Quarto quarto = quartoDao.buscarPorId((int) tabelaQuartos.getValueAt(tabelaQuartos.getSelectedRow(), 0));
            
            if (!quarto.isDisponivel()) {
                op = JOptionPane.showConfirmDialog(this, "Existem hóspedes com reservas neste quarto.\n"
                        + "Todas as reservas relacionadas ao quarto também serão excluidas.\nDeseja prosseguir?",
                        "Exclusão", JOptionPane.YES_NO_OPTION);
                if(op==JOptionPane.YES_OPTION){
                    ReservaDAO reservaDao = new ReservaDAO();
                    List<Reserva> reservas = reservaDao.buscarPorQuarto(quarto);
                    
                    for (Reserva reserva : reservas) {
                        reservaDao.excluir(reserva);
                    }
                    JOptionPane.showMessageDialog(this, "Reservas relacionadas ao quarto excluidas!");
                }else{
                    return;
                }
            }
            JOptionPane.showMessageDialog(this, "Quarto excluido!");
            quartoDao.excluir(quarto);

            pesquisar(modelo);
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaQuarto.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TelaQuarto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnExcluirQuartoActionPerformed

    private void btnNovoQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoQuartoActionPerformed
        new TelaCadastroQuarto().setVisible(true);
    }//GEN-LAST:event_btnNovoQuartoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaQuarto.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaQuarto.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaQuarto.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaQuarto.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaQuarto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarQuarto;
    private javax.swing.JButton btnExcluirQuarto;
    private javax.swing.JButton btnNovoQuarto;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelaQuartos;
    // End of variables declaration//GEN-END:variables

}
